// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PGS
{
        public const string achievement_16 = "CgkI68nRrdwNEAIQDA"; // <GPGSID>
        public const string achievement_question = "CgkI68nRrdwNEAIQDQ"; // <GPGSID>
        public const string achievement_9 = "CgkI68nRrdwNEAIQCg"; // <GPGSID>
        public const string achievement_2 = "CgkI68nRrdwNEAIQAw"; // <GPGSID>
        public const string achievement_3 = "CgkI68nRrdwNEAIQBA"; // <GPGSID>
        public const string achievement_1 = "CgkI68nRrdwNEAIQAg"; // <GPGSID>
        public const string achievement_6 = "CgkI68nRrdwNEAIQBw"; // <GPGSID>
        public const string achievement_7 = "CgkI68nRrdwNEAIQCA"; // <GPGSID>
        public const string achievement_4 = "CgkI68nRrdwNEAIQBQ"; // <GPGSID>
        public const string achievement_5 = "CgkI68nRrdwNEAIQBg"; // <GPGSID>
        public const string achievement_8 = "CgkI68nRrdwNEAIQCQ"; // <GPGSID>
        public const string achievement_10 = "CgkI68nRrdwNEAIQCw"; // <GPGSID>
        public const string leaderboard_place = "CgkI68nRrdwNEAIQAA"; // <GPGSID>

}

